/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    id("application")
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("org.javamodularity.moduleplugin") version "1.8.12"
    id("com.gluonhq.gluonfx-gradle-plugin") version "1.0.28"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

java {
    modularity.inferModulePath.set(false)
}

javafx {
    version = "23"
    modules("javafx.controls")
}

gluonfx {
    target = "host"
    attachConfig.version = "4.0.24"
    attachConfig.services("settings", "storage", "browser")
}

dependencies {
//    api(libs.org.openjfx.javafx.controls)
    api(libs.com.gluonhq.attach.settings)
    api(libs.com.gluonhq.attach.storage)
    api(libs.com.gluonhq.attach.browser)
    api(libs.org.kordamp.ikonli.ikonli.javafx)
    api(libs.org.kordamp.ikonli.ikonli.fontawesome6.pack)
    api(libs.io.github.mkpaz.atlantafx.base)
    api(libs.it.unimi.dsi.fastutil.core)
    api(libs.tools.jackson.core.jackson.databind)
    api(libs.com.dropbox.core.dropbox.core.sdk)
//    implementation("com.dropbox.core:dropbox-core-sdk:7.0.0")
    api(libs.org.jetbrains.annotations)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

group = "ninjamica"
version = "1.0-SNAPSHOT"
description = "TaskTwig"
java.sourceCompatibility = JavaVersion.VERSION_25

application {
    mainClass.set("ninjamica.tasktwig.ui.Launcher") // Specify your main entry point
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
//    options.compilerArgs.addAll(arrayOf("--add-modules", "com.dropbox.core"))
}

tasks.register("printRuntimeClasspath") {
    doLast {
        println(sourceSets.main.get().runtimeClasspath.asPath)
    }
}

tasks.named<JavaExec>("run") {
    classpath = files("build/classes/java/main", "build/resources/main") +
            configurations.getByName("runtimeClasspath")
    mainClass.set("ninjamica.tasktwig.ui.Launcher")
    workingDir = project.projectDir
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
